### ISSUE TITLE
generate module in nowhere doesn't work

### ISSUE THREAD

**Issue by rbalet** [cyrilletuzi/vscode-angular-schematics#151]
# Description of the issue
I'm not able to generate a module `Module of components` with `Nowhere`

# How to reproduce the issue
1.  `ng new angular-test`
2.  add routing and scss
3.  create inside the app folder an folder `test`
4.  click on the folder and generate a module -> `Module of components` -> `Nowhere`

# log
```shell
ng g module test/ --module Nowhere
Specified module 'Nowhere' does not exist.
Looked in the following directories:
    /src/app/Nowhere
    /src/app/test
    /src/app
    /src
```

# version
```shell
Angular CLI: 9.1.4
Node: 12.13.1
OS: win32 x64
```

**Comment by cyrilletuzi** [comment]
Thanks for the report. It is fixed in v4.0.5.

For info: v4 was a full rewrite of the extension. It took more than a full-time non-paid week to do this rewrite. Yet I still do not have any sponsor. So please consider to help, or to ask your enterprise, which makes money with this extension, to help.
