### ISSUE TITLE
Command 'Angular Schematics: Show schematics list (internal command)' resulted in an error (command 'ngschematics.showtree' not found)

### ISSUE THREAD

**Issue by sugidaffection** [cyrilletuzi/vscode-angular-schematics#903]
Command 'Angular Schematics: Show schematics list (internal command)' resulted in an error (command 'ngschematics.showtree' not found)

<div align="center">
<img  width="256" alt="command 'ngschematics.showtree' not found" src="https://user-images.githubusercontent.com/21971925/187019389-6f283807-f923-47e8-9e83-b733dd33dde5.png">
</div>

<div align="center">
<img width="259" alt="command 'ngschematics.documentation' not found" src="https://user-images.githubusercontent.com/21971925/187019523-33916a08-990c-412a-bb58-8cf09488de77.png">
</div>

i need to re-enable the extensions to solve this problem

**Comment by cyrilletuzi** [comment]
> i need to re-enable the extensions to solve this problem

Can you elaborate about this? What special action results in having to re-enable the extension?

**Comment by sugidaffection** [comment]
<img width="610" alt="Screen Shot 2022-08-29 at 15 20 05" src="https://user-images.githubusercontent.com/21971925/187157091-9e994f29-ff8c-4481-aa3e-ac22aa035a52.png">
<img width="306" alt="Screen Shot 2022-08-29 at 15 20 26" src="https://user-images.githubusercontent.com/21971925/187157114-d84d4ab4-d29e-4cf5-9b26-082db097fb7f.png">

the extension is not working
i have to re-enable the extension
<img width="362" alt="Screen Shot 2022-08-29 at 15 22 49" src="https://user-images.githubusercontent.com/21971925/187157631-121b0579-749a-4b5f-bef0-6649a26e01f8.png">
<img width="424" alt="Screen Shot 2022-08-29 at 15 22 58" src="https://user-images.githubusercontent.com/21971925/187157619-e8c7767a-504d-4a7e-915f-0852d4ac9ddd.png">

then the extension working properly
<img width="357" alt="Screen Shot 2022-08-29 at 15 23 14" src="https://user-images.githubusercontent.com/21971925/187157832-1ab9b184-c93b-4b9a-96f9-562a347a64d7.png">


it happened every i open/re-open vscode

**Comment by cyrilletuzi** [comment]
OK so you are trying to use this command because the generation options ("Angular: Generate...") in the context menu are missing.

The "Show schematics list" command is not related at all to the generation options appearing in the context menu.

It seems you have a more general issue with the extension activation. So I will close this issue and ask you to open a new one, but this time following the provided issue template, which is here to solve most of this kind of issues (so you will probably not have to post a new issue at all), or if there is still an issue, so I have some information to be able to help you, because currently I have no information at all to locate (and solve) the problem.
