### ISSUE TITLE
Extension is using "defaultCollection" in angular.json to specify other schematics like NGRX, but that is now deprecated in Angular 14 in favor of "schematicCollections.

### ISSUE THREAD

**Issue by bit7** [cyrilletuzi/vscode-angular-schematics#905]
Extension is using "defaultCollection" in angular.json to specify other schematics like NGRX, but that is now deprecated in Angular 14 in favor of "schematicCollections.

Below you can see what I am talking about.
"cli": {
    "defaultCollection": "@ngrx/schematics", 
    // defaultCollection is deprecated in Angular 14, but still works.  
    // Upgrading to 14 removes "defaultCollection" though.
    "schematicCollections": [                               
    // schematicCollections is what to be used going forward because it accepts an array of values.
      "@ngrx/schematics"
    ],
    "analytics": false
  }
![image](https://user-images.githubusercontent.com/2263077/206009106-715eee1e-2720-40df-b70b-ab732c78d3e8.png)
![image](https://user-images.githubusercontent.com/2263077/206009270-34dbfa01-c184-4d40-a6d3-d1e64bf5386a.png)

**Comment by cyrilletuzi** [comment]
I am gonna close this issue for these reasons:

1. Angular CLI 14 configuration change was already taken into consideration in #893

2. I do not understand the problem (if there is one), among others things because this statement is false:

> Extension is using "defaultCollection" in angular.json to specify other schematics like NGRX

Default collection for shorcuts ("Generate a component / service / module") is, has always been and will always be the official Angular schematics, as already discussed [here](https://github.com/cyrilletuzi/vscode-angular-schematics/discussions/453#discussioncomment-2606974).

Detection of other collections didn't need the `angular.json` configuration.

3. You did not follow the issue template, so even if there was an issue, I do not have the information to help.
